### ISSUE TITLE
[RE] Crash calling a batch under Windows

### ISSUE THREAD

**Issue by TigersWay** [grmartin/gulp-connect-php#1]
Hi,
These following lines are in my gulpfile:
```
  php.server({
//    bin: 'php.bat',
    base: 'public'
  }, function () {
    browserSync.init({
//      files: ['**/*.php'],
      proxy: 'localhost:8000',
      browser: ['firefox']
    })
  });
```
It breaks... like this (if I can provide you with anything else...)

```[22:17:58] Starting 'default'...
[22:18:13] Finished 'default' after 15 s
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn php ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
With the comment off, everything runs fine.
My php.exe is somewhere in some deep path, installed with UwAmp. But I have a quick access php.bat on the PATH.

**Comment by grmartin** [comment]
can you set the environment variable NODE_DEBUG to 'child_process' and rerun... itll tell me exactly what is being invoked (i hope)

**Comment by grmartin** [comment]
@TigersWay So, Windows Batch files are not 'executable' in the classic sense. They need to be thought of as being more like an Interpreted Language... The Interpreter (in this case `cmd.exe`) must be invoked and a shell session created for a Batch file to be seen as an executable.

Try something like this:

```js
  php.server({
//    bin: 'php.bat',
    base: 'public', 
    configCallback: function _configCallback(type, collection) { // The change is this function
      if (type === connect.OPTIONS_SPAWN_OBJ) {
        // Windows Batch files are NOT executable on their own. This will start a shell 
        // session then execute.
        collection.shell = true;
        return collection;
      }
    }
  }, function () {
    browserSync.init({
//      files: ['**/*.php'],
      proxy: 'localhost:8000',
      browser: ['firefox']
    })
  });
```

A concrete example with additional notes can be found here: 
https://github.com/micahblu/gulp-connect-php#windows-via-batch-file

Oh also @TigersWay 1.0.0 was merged in to the mainline.

(On a side note, i make it a habit to name anonymous functions, thus `_configCallback` in the example (`configCallback: function _configCallback(type, collection)`) is the name... I do this to make stack traces more informative... However you could just as easily use `configCallback: function (type, collection)` or `configCallback: (type, collection) => {` (last one is untested, but since we dont rely on `this` it should work fine))

**Comment by TigersWay** [comment]
Yes, the new README is a lot more precise and I'm probably going to correct all my gulpfiles :-) 
But `bin: 'php.bat'` seemed to be enough.

... Loading the last release!
